export const START_FETCH_SEARCH_MOVIES = 'START_FETCH_SEARCH_MOVIES'
export const FETCH_SEARCH_MOVIES_SUCCESS = 'FETCH_SEARCH_MOVIES_SUCCESS'
export const FETCH_SEARCH_MOVIES_FAIL = 'FETCH_SEARCH_MOVIES_FAIL'
