// movies
export const START_FETCH_SEARCH_MOVIES = 'START_FETCH_SEARCH_MOVIES'
export const FETCH_SEARCH_MOVIES_SUCCESS = 'FETCH_SEARCH_MOVIES_SUCCESS'
export const FETCH_SEARCH_MOVIES_FAIL = 'FETCH_SEARCH_MOVIES_FAIL'
export const START_FETCH_POPULAR_MOVIES = 'START_FETCH_POPULAR_MOVIES'
export const FETCH_POPULAR_MOVIES_SUCCESS = 'FETCH_POPULAR_MOVIES_SUCCESS'
export const FETCH_POPULAR_MOVIES_FAIL = 'FETCH_POPULAR_MOVIES_FAIL'
export const START_FETCH_TRENDING_MOVIES = 'START_FETCH_TRENDING_MOVIES'
export const FETCH_TRENDING_MOVIES_SUCCESS = 'FETCH_TRENDING_MOVIES_SUCCESS'
export const FETCH_TRENDING_MOVIES_FAIL = 'FETCH_TRENDING_MOVIES_FAIL'

// movie
export const START_FETCH_MOVIE_DETAILS = 'START_FETCH_MOVIE_DETAILS'
export const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS'
export const FETCH_MOVIE_DETAILS_FAIL = 'FETCH_MOVIE_DETAILS_FAIL'

// person
export const START_FETCH_PERSON = 'START_FETCH_PERSON'
export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS'
export const FETCH_PERSON_FAIL = 'FETCH_PERSON_FAIL'
